export const END_GAME = "END_GAME";
export const GAME_MOVE = "GAME_MOVE";
export const NEW_GAME = "NEW_GAME";
export const SETTING_MODE = "SETTING_MODE";
export const SETTING_PLAYER_SYMBOL = "SETTING_PLAYER_SYMBOL";
export const SETTING_SIZE_FIELD = "SETTING_SIZE_FIELD";
export const SETTING_TURN = "SETTING_TURN";
export const SETTING_VICTORY_CELL = "SETTING_VICTORY_CELL";